// Generated by gencpp from file dynamixel_current_2port/Emergency.msg
// DO NOT EDIT!


#ifndef DYNAMIXEL_CURRENT_2PORT_MESSAGE_EMERGENCY_H
#define DYNAMIXEL_CURRENT_2PORT_MESSAGE_EMERGENCY_H

#include <ros/service_traits.h>


#include <dynamixel_current_2port/EmergencyRequest.h>
#include <dynamixel_current_2port/EmergencyResponse.h>


namespace dynamixel_current_2port
{

struct Emergency
{

typedef EmergencyRequest Request;
typedef EmergencyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Emergency
} // namespace dynamixel_current_2port


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dynamixel_current_2port::Emergency > {
  static const char* value()
  {
    return "04c66b9168769803386104918010c5ae";
  }

  static const char* value(const ::dynamixel_current_2port::Emergency&) { return value(); }
};

template<>
struct DataType< ::dynamixel_current_2port::Emergency > {
  static const char* value()
  {
    return "dynamixel_current_2port/Emergency";
  }

  static const char* value(const ::dynamixel_current_2port::Emergency&) { return value(); }
};


// service_traits::MD5Sum< ::dynamixel_current_2port::EmergencyRequest> should match
// service_traits::MD5Sum< ::dynamixel_current_2port::Emergency >
template<>
struct MD5Sum< ::dynamixel_current_2port::EmergencyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dynamixel_current_2port::Emergency >::value();
  }
  static const char* value(const ::dynamixel_current_2port::EmergencyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dynamixel_current_2port::EmergencyRequest> should match
// service_traits::DataType< ::dynamixel_current_2port::Emergency >
template<>
struct DataType< ::dynamixel_current_2port::EmergencyRequest>
{
  static const char* value()
  {
    return DataType< ::dynamixel_current_2port::Emergency >::value();
  }
  static const char* value(const ::dynamixel_current_2port::EmergencyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dynamixel_current_2port::EmergencyResponse> should match
// service_traits::MD5Sum< ::dynamixel_current_2port::Emergency >
template<>
struct MD5Sum< ::dynamixel_current_2port::EmergencyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dynamixel_current_2port::Emergency >::value();
  }
  static const char* value(const ::dynamixel_current_2port::EmergencyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dynamixel_current_2port::EmergencyResponse> should match
// service_traits::DataType< ::dynamixel_current_2port::Emergency >
template<>
struct DataType< ::dynamixel_current_2port::EmergencyResponse>
{
  static const char* value()
  {
    return DataType< ::dynamixel_current_2port::Emergency >::value();
  }
  static const char* value(const ::dynamixel_current_2port::EmergencyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DYNAMIXEL_CURRENT_2PORT_MESSAGE_EMERGENCY_H
