// Generated by gencpp from file dynamixel_current_2port/RL_NeckAngle.msg
// DO NOT EDIT!


#ifndef DYNAMIXEL_CURRENT_2PORT_MESSAGE_RL_NECKANGLE_H
#define DYNAMIXEL_CURRENT_2PORT_MESSAGE_RL_NECKANGLE_H

#include <ros/service_traits.h>


#include <dynamixel_current_2port/RL_NeckAngleRequest.h>
#include <dynamixel_current_2port/RL_NeckAngleResponse.h>


namespace dynamixel_current_2port
{

struct RL_NeckAngle
{

typedef RL_NeckAngleRequest Request;
typedef RL_NeckAngleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RL_NeckAngle
} // namespace dynamixel_current_2port


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dynamixel_current_2port::RL_NeckAngle > {
  static const char* value()
  {
    return "53641ec2b7d57c4826404748be4e88f1";
  }

  static const char* value(const ::dynamixel_current_2port::RL_NeckAngle&) { return value(); }
};

template<>
struct DataType< ::dynamixel_current_2port::RL_NeckAngle > {
  static const char* value()
  {
    return "dynamixel_current_2port/RL_NeckAngle";
  }

  static const char* value(const ::dynamixel_current_2port::RL_NeckAngle&) { return value(); }
};


// service_traits::MD5Sum< ::dynamixel_current_2port::RL_NeckAngleRequest> should match
// service_traits::MD5Sum< ::dynamixel_current_2port::RL_NeckAngle >
template<>
struct MD5Sum< ::dynamixel_current_2port::RL_NeckAngleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dynamixel_current_2port::RL_NeckAngle >::value();
  }
  static const char* value(const ::dynamixel_current_2port::RL_NeckAngleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dynamixel_current_2port::RL_NeckAngleRequest> should match
// service_traits::DataType< ::dynamixel_current_2port::RL_NeckAngle >
template<>
struct DataType< ::dynamixel_current_2port::RL_NeckAngleRequest>
{
  static const char* value()
  {
    return DataType< ::dynamixel_current_2port::RL_NeckAngle >::value();
  }
  static const char* value(const ::dynamixel_current_2port::RL_NeckAngleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dynamixel_current_2port::RL_NeckAngleResponse> should match
// service_traits::MD5Sum< ::dynamixel_current_2port::RL_NeckAngle >
template<>
struct MD5Sum< ::dynamixel_current_2port::RL_NeckAngleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dynamixel_current_2port::RL_NeckAngle >::value();
  }
  static const char* value(const ::dynamixel_current_2port::RL_NeckAngleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dynamixel_current_2port::RL_NeckAngleResponse> should match
// service_traits::DataType< ::dynamixel_current_2port::RL_NeckAngle >
template<>
struct DataType< ::dynamixel_current_2port::RL_NeckAngleResponse>
{
  static const char* value()
  {
    return DataType< ::dynamixel_current_2port::RL_NeckAngle >::value();
  }
  static const char* value(const ::dynamixel_current_2port::RL_NeckAngleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DYNAMIXEL_CURRENT_2PORT_MESSAGE_RL_NECKANGLE_H
