// Generated by gencpp from file dynamixel_current_2port/SendMotion.msg
// DO NOT EDIT!


#ifndef DYNAMIXEL_CURRENT_2PORT_MESSAGE_SENDMOTION_H
#define DYNAMIXEL_CURRENT_2PORT_MESSAGE_SENDMOTION_H

#include <ros/service_traits.h>


#include <dynamixel_current_2port/SendMotionRequest.h>
#include <dynamixel_current_2port/SendMotionResponse.h>


namespace dynamixel_current_2port
{

struct SendMotion
{

typedef SendMotionRequest Request;
typedef SendMotionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SendMotion
} // namespace dynamixel_current_2port


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dynamixel_current_2port::SendMotion > {
  static const char* value()
  {
    return "d1639d81e320e2f0297d5f30ecc057d5";
  }

  static const char* value(const ::dynamixel_current_2port::SendMotion&) { return value(); }
};

template<>
struct DataType< ::dynamixel_current_2port::SendMotion > {
  static const char* value()
  {
    return "dynamixel_current_2port/SendMotion";
  }

  static const char* value(const ::dynamixel_current_2port::SendMotion&) { return value(); }
};


// service_traits::MD5Sum< ::dynamixel_current_2port::SendMotionRequest> should match
// service_traits::MD5Sum< ::dynamixel_current_2port::SendMotion >
template<>
struct MD5Sum< ::dynamixel_current_2port::SendMotionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dynamixel_current_2port::SendMotion >::value();
  }
  static const char* value(const ::dynamixel_current_2port::SendMotionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dynamixel_current_2port::SendMotionRequest> should match
// service_traits::DataType< ::dynamixel_current_2port::SendMotion >
template<>
struct DataType< ::dynamixel_current_2port::SendMotionRequest>
{
  static const char* value()
  {
    return DataType< ::dynamixel_current_2port::SendMotion >::value();
  }
  static const char* value(const ::dynamixel_current_2port::SendMotionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dynamixel_current_2port::SendMotionResponse> should match
// service_traits::MD5Sum< ::dynamixel_current_2port::SendMotion >
template<>
struct MD5Sum< ::dynamixel_current_2port::SendMotionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dynamixel_current_2port::SendMotion >::value();
  }
  static const char* value(const ::dynamixel_current_2port::SendMotionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dynamixel_current_2port::SendMotionResponse> should match
// service_traits::DataType< ::dynamixel_current_2port::SendMotion >
template<>
struct DataType< ::dynamixel_current_2port::SendMotionResponse>
{
  static const char* value()
  {
    return DataType< ::dynamixel_current_2port::SendMotion >::value();
  }
  static const char* value(const ::dynamixel_current_2port::SendMotionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DYNAMIXEL_CURRENT_2PORT_MESSAGE_SENDMOTION_H
