// Generated by gencpp from file dynamixel_current_2port/UD_NeckAngle.msg
// DO NOT EDIT!


#ifndef DYNAMIXEL_CURRENT_2PORT_MESSAGE_UD_NECKANGLE_H
#define DYNAMIXEL_CURRENT_2PORT_MESSAGE_UD_NECKANGLE_H

#include <ros/service_traits.h>


#include <dynamixel_current_2port/UD_NeckAngleRequest.h>
#include <dynamixel_current_2port/UD_NeckAngleResponse.h>


namespace dynamixel_current_2port
{

struct UD_NeckAngle
{

typedef UD_NeckAngleRequest Request;
typedef UD_NeckAngleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct UD_NeckAngle
} // namespace dynamixel_current_2port


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dynamixel_current_2port::UD_NeckAngle > {
  static const char* value()
  {
    return "54d0093350d66ae9f81f65f132656855";
  }

  static const char* value(const ::dynamixel_current_2port::UD_NeckAngle&) { return value(); }
};

template<>
struct DataType< ::dynamixel_current_2port::UD_NeckAngle > {
  static const char* value()
  {
    return "dynamixel_current_2port/UD_NeckAngle";
  }

  static const char* value(const ::dynamixel_current_2port::UD_NeckAngle&) { return value(); }
};


// service_traits::MD5Sum< ::dynamixel_current_2port::UD_NeckAngleRequest> should match
// service_traits::MD5Sum< ::dynamixel_current_2port::UD_NeckAngle >
template<>
struct MD5Sum< ::dynamixel_current_2port::UD_NeckAngleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dynamixel_current_2port::UD_NeckAngle >::value();
  }
  static const char* value(const ::dynamixel_current_2port::UD_NeckAngleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dynamixel_current_2port::UD_NeckAngleRequest> should match
// service_traits::DataType< ::dynamixel_current_2port::UD_NeckAngle >
template<>
struct DataType< ::dynamixel_current_2port::UD_NeckAngleRequest>
{
  static const char* value()
  {
    return DataType< ::dynamixel_current_2port::UD_NeckAngle >::value();
  }
  static const char* value(const ::dynamixel_current_2port::UD_NeckAngleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dynamixel_current_2port::UD_NeckAngleResponse> should match
// service_traits::MD5Sum< ::dynamixel_current_2port::UD_NeckAngle >
template<>
struct MD5Sum< ::dynamixel_current_2port::UD_NeckAngleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dynamixel_current_2port::UD_NeckAngle >::value();
  }
  static const char* value(const ::dynamixel_current_2port::UD_NeckAngleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dynamixel_current_2port::UD_NeckAngleResponse> should match
// service_traits::DataType< ::dynamixel_current_2port::UD_NeckAngle >
template<>
struct DataType< ::dynamixel_current_2port::UD_NeckAngleResponse>
{
  static const char* value()
  {
    return DataType< ::dynamixel_current_2port::UD_NeckAngle >::value();
  }
  static const char* value(const ::dynamixel_current_2port::UD_NeckAngleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DYNAMIXEL_CURRENT_2PORT_MESSAGE_UD_NECKANGLE_H
